# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'seminar-2-assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seminar-2-assignment

end

pod 'Alamofire'