# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'seminar-4-assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seminar-4-assignment
  pod 'RxSwift', '~> 6.5'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'RxDataSources', '~>5.0.0'
  pod 'Alamofire', '~> 5.6.2'

end
